Repository graphene-monitoring/graphene, pull requests merged in 2019-11, with the labels that each got.

#14 Feature: add index rotating read feature
  .circleci/config.yml
  README.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  graphene-common/build.gradle
  graphene-common/src/main/java/net/iponweb/disthene/reader/utils/DateTimeUtils.java
  graphene-common/src/main/kotlin/com/graphene/common/key/RotationProperty.kt
  graphene-common/src/main/kotlin/com/graphene/common/key/RotationStrategy.kt
  graphene-common/src/main/kotlin/com/graphene/common/rule/GrapheneRules.kt
  graphene-common/src/main/kotlin/com/graphene/common/utils/DateTimeUtils.kt
  graphene-common/src/test/java/net/iponweb/disthene/reader/utils/WildcardUtilTest.java
  graphene-common/src/test/kotlin/com/graphene/common/utils/DateTimeUtilsTest.kt
  graphene-common/src/test/kotlin/net/iponweb/disthene/reader/utils/WildcardUtilTest.kt
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/evaluation/TargetEvaluator.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/HitcountFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/MovingAverageFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/MovingMaxFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/MovingMedianFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/MovingMinFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/StdevFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/SummarizeFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/TimeShiftFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/TimeStackFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/service/index/IndexService.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/service/metric/CassandraMetricService.java
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphite/GraphiteController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphite/request/MetricsFindRequest.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/ElasticsearchClient.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/ElasticsearchKeySearchHandler.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/KeySelector.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/KeySelectorProperty.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/RollingKeySelector.kt
  graphene-reader/src/main/resources/application.yml
  graphene-reader/src/test/kotlin/com/graphene/reader/service/index/ElasticsearchIndexServiceTest.kt
  graphene-reader/src/test/kotlin/com/graphene/reader/store/key/selector/RollingKeySelectorTest.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/GrapheneWriterApplication.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/influxdb/InfluxDbController.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/influxdb/InfluxDbMetricConverter.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexRollingEsClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/SimpleKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/RotationProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/RotationStrategy.kt
  graphene-writer/src/test/kotlin/com/graphene/writer/store/key/property/TimeBasedRotationStrategyTest.kt
Labels: enhancement

#16 refactor: bump up elasticsearch client version and additional property
  RELEASE_NOTES.md
  build.gradle
  docker-compose.yml
  graphene-docker/docker-compose.yml
  graphene-docker/graphene-reader/Dockerfile
  graphene-docker/graphene-writer/Dockerfile
  graphene-reader/build.gradle
  graphene-reader/src/main/java/net/iponweb/disthene/reader/handler/RenderHandler.java
  graphene-writer/build.gradle
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/SimpleKeyStoreHandler.kt
Labels: enhancement

#18 feat: support past metric indexing based on metric timestamp
  graphene-common/src/main/kotlin/com/graphene/common/key/RotationStrategy.kt
  graphene-common/src/main/kotlin/com/graphene/common/rule/GrapheneRules.kt
  graphene-reader/src/main/resources/application.yml
  graphene-writer/src/main/kotlin/com/graphene/writer/input/GrapheneMetric.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/influxdb/InfluxDbController.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/influxdb/InfluxDbMetricConverter.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraDataStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientTemplate.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/GrapheneIndexRequest.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexRollingEsClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/SimpleKeyStoreHandler.kt
  graphene-writer/src/main/resources/application.yml
  graphene-writer/src/test/kotlin/com/graphene/writer/store/key/property/TimeBasedRotationStrategyTest.kt
Labels: bug

#20 add bulkAsync feature for indexing performance
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientTemplate.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
Labels: enhancement

#21 bugfix: Ignore unavailable index when read.
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/ElasticsearchClient.kt
Labels: bug

#25 feat: add KeyCache interface for checking duplication metric key
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/KeyCache.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/MultiGetRequestContainer.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/TimeBasedLocalKeyCache.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/test/kotlin/com/graphene/writer/store/key/handler/TimeBasedLocalKeyCacheTest.kt
Labels: bug

#23 bugfix: Improve Key Store throughput
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/KeyCache.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/MultiGetRequestContainer.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/TimeBasedLocalKeyCache.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/test/kotlin/com/graphene/writer/store/key/handler/TimeBasedLocalKeyCacheTest.kt
Labels: bug, enhancement

#24 bugfix: Prevent calling clearScroll if there's no scrollId.
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/ElasticsearchKeySearchHandler.kt
Labels: bug

#26 Bugfix/function patches 0
  graphene-common/build.gradle
  graphene-function/build.gradle
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/PathTarget.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/evaluation/TargetEvaluator.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/DistheneFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/SumSeriesWithWildcardsFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/TimeShiftFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/TimeStackFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/service/metric/MetricService.java
  graphene-reader/build.gradle
  graphene-reader/src/main/java/net/iponweb/disthene/reader/service/metric/CassandraMetricService.java
  graphene-reader/src/main/kotlin/com/graphene/reader/handler/RenderParameter.kt
  graphene-writer/build.gradle
Labels: bug, enhancement
