Repository graphene-monitoring/graphene, pull requests merged in 2019-10, with the labels that each got.

#2 feature: aliasByNode function now supports minus index
  graphene-common/src/main/java/net/iponweb/disthene/reader/utils/TimeSeriesUtils.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/AliasByNodeFunction.java
  graphene-function/src/main/java/net/iponweb/disthene/reader/graphite/functions/DistheneFunction.java
Labels: enhancement

#3 Feature: Feature/key store handler
  build.gradle
  graphene-common/src/main/java/net/iponweb/disthene/reader/handler/response/HierarchyMetricPath.java
  graphene-common/src/main/kotlin/com/graphene/common/HierarchyMetricPaths.kt
  graphene-common/src/test/java/net/iponweb/disthene/reader/utils/WildcardUtilTest.java
  graphene-common/src/test/kotlin/com/graphene/common/HierarchyMetricPathsTest.kt
  graphene-function/src/main/java/net/iponweb/disthene/reader/service/index/IndexService.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/handler/RenderHandler.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/service/index/ElasticsearchIndexService.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/service/metric/CassandraMetricService.java
  graphene-reader/src/main/kotlin/com/graphene/reader/config/GrapheneReaderConfiguration.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphene/PathsController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphene/PathsStatsController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphene/SearchController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphite/GraphiteController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/ElasticsearchClient.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/ElasticsearchIndexService.kt
  graphene-reader/src/test/kotlin/com/graphene/reader/service/index/ElasticsearchIndexServiceTest.kt
  graphene-reader/src/test/net/iponweb/disthene/reader/handler/response/HierarchyMetricPathTest.java
  graphene-writer/src/main/kotlin/com/graphene/writer/config/CassandraDataStoreConfiguration.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/config/ElasticsearchKeyStoreConfiguration.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/GrapheneMetric.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/GraphiteAware.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/GraphiteMetric.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/StoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraLoadBalancingPolicies.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraLoadBalancingPolicy.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/GrapheneKeyMapper.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexThread.kt
Labels: enhancement

#6 Feature/multiple handler using property
  docs/wiki/Home/Concepts.drawio
  docs/wiki/Home/Concepts.png
  graphene-writer/src/main/kotlin/com/graphene/writer/GrapheneWriterApplication.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/config/GrapheneWriterConfiguration.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/config/StatsProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/event/GrapheneWriterEventListener.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/MetricConverter.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/CarbonServer.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/CarbonServerHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/GraphiteMetricConverter.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/property/CarbonProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/input/graphite/property/GraphiteInputProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/GrapheneStoreConfig.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/StoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraDataStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraDataStoreHandlerProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/CassandraFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/data/StoreDataProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/LoggingKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/SimpleKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/model/ElasticsearchFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/model/GrapheneKeyMapper.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/model/SimpleKeyStoreHandlerProperty.kt
  graphene-writer/src/main/resources/application.yml
  graphene-writer/src/test/kotlin/com/graphene/writer/input/graphite/GraphiteMetricConverterTest.kt
Labels: enhancement

#8 fix: fix the bug which return ']' single string at empty time series
  graphene-reader/src/main/java/net/iponweb/disthene/reader/format/ResponseFormatter.java
  graphene-reader/src/test/kotlin/net/iponweb/disthene/reader/format/ResponseFormatterTest.java
Labels: bug

#10 Performance optimization on Controller.
  graphene-reader/src/main/java/net/iponweb/disthene/reader/format/ResponseFormatter.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/handler/RenderHandler.java
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphite/GraphiteController.kt
Labels: enhancement

#12 Docs/key store architecture
  docs/wiki/Home/Key-Store-Architecture.png
Labels: documentation

#13 Feature : add index rotating feature
  build.gradle
  docs/wiki/Home/Key-Store-Architecture.png
  graphene-function/src/main/java/net/iponweb/disthene/reader/service/index/IndexService.java
  graphene-reader/build.gradle
  graphene-reader/src/main/java/net/iponweb/disthene/reader/GrapheneReaderApplication.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/handler/RenderHandler.java
  graphene-reader/src/main/java/net/iponweb/disthene/reader/service/metric/CassandraMetricService.java
  graphene-reader/src/main/kotlin/com/graphene/reader/controller/graphite/GraphiteController.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/ElasticsearchClient.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/service/index/model/IndexProperty.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/ElasticsearchKeySearchHandler.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/KeySelector.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/KeySelectorProperty.kt
  graphene-reader/src/main/kotlin/com/graphene/reader/store/key/selector/RollingKeySelector.kt
  graphene-reader/src/main/resources/application.yml
  graphene-reader/src/test/kotlin/com/graphene/reader/service/index/ElasticsearchIndexServiceTest.kt
  graphene-reader/src/test/kotlin/com/graphene/reader/store/key/selector/RollingKeySelectorTest.kt
  graphene-reader/src/test/kotlin/net/iponweb/disthene/reader/format/ResponseFormatterTest.java
  graphene-writer/src/main/kotlin/com/graphene/writer/GrapheneWriterApplication.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/ElasticsearchClientTemplate.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/GrapheneIndexRequest.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/IndexRollingEsClient.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/AbstractElasticsearchKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/IndexBasedKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/LoggingKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/handler/SimpleKeyStoreHandler.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/model/ElasticsearchFactory.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/model/GrapheneKeyMapper.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/ElasticsearchKeyStoreHandlerProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/IndexBasedKeyStoreHandlerProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/RotationProperty.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/RotationStrategy.kt
  graphene-writer/src/main/kotlin/com/graphene/writer/store/key/property/SimpleKeyStoreHandlerProperty.kt
  graphene-writer/src/main/resources/application.yml
  graphene-writer/src/test/kotlin/com/graphene/writer/store/key/property/TimeBasedRotationStrategyTest.kt
Labels: enhancement
